[2023-04-26T15:01:22.427+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag_api.cities.process_data_Zhmerynka manual__2023-04-26T15:00:51.829131+00:00 [queued]>
[2023-04-26T15:01:22.501+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag_api.cities.process_data_Zhmerynka manual__2023-04-26T15:00:51.829131+00:00 [queued]>
[2023-04-26T15:01:22.509+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T15:01:22.511+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-26T15:01:22.512+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T15:01:22.830+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): cities.process_data_Zhmerynka> on 2023-04-26 15:00:51.829131+00:00
[2023-04-26T15:01:22.849+0000] {standard_task_runner.py:55} INFO - Started process 2128 to run task
[2023-04-26T15:01:22.890+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather_dag_api', 'cities.process_data_Zhmerynka', 'manual__2023-04-26T15:00:51.829131+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag_api.py', '--cfg-path', '/tmp/tmpt_cunggw']
[2023-04-26T15:01:22.893+0000] {standard_task_runner.py:83} INFO - Job 76: Subtask cities.process_data_Zhmerynka
[2023-04-26T15:01:23.574+0000] {task_command.py:389} INFO - Running <TaskInstance: weather_dag_api.cities.process_data_Zhmerynka manual__2023-04-26T15:00:51.829131+00:00 [running]> on host d48b88797b3b
[2023-04-26T15:01:24.255+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_dag_api
AIRFLOW_CTX_TASK_ID=cities.process_data_Zhmerynka
AIRFLOW_CTX_EXECUTION_DATE=2023-04-26T15:00:51.829131+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-26T15:00:51.829131+00:00
[2023-04-26T15:01:24.354+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/weather_dag_api.py", line 31, in process_weather_data
    print(info["data"][0]["coordinates"][0]["dates"][0]["value"])
TypeError: 'NoneType' object is not subscriptable
[2023-04-26T15:01:24.451+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=weather_dag_api, task_id=cities.process_data_Zhmerynka, execution_date=20230426T150051, start_date=20230426T150122, end_date=20230426T150124
[2023-04-26T15:01:24.546+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 76 for task cities.process_data_Zhmerynka ('NoneType' object is not subscriptable; 2128)
[2023-04-26T15:01:24.623+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-26T15:01:25.072+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
