[2023-04-25T20:26:56.652+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag_api.extract_data manual__2023-04-25T20:26:33.610694+00:00 [queued]>
[2023-04-25T20:26:56.698+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag_api.extract_data manual__2023-04-25T20:26:33.610694+00:00 [queued]>
[2023-04-25T20:26:56.700+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T20:26:56.702+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-25T20:26:56.703+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T20:26:56.751+0000] {taskinstance.py:1309} INFO - Executing <Task(SimpleHttpOperator): extract_data> on 2023-04-25 20:26:33.610694+00:00
[2023-04-25T20:26:56.770+0000] {standard_task_runner.py:55} INFO - Started process 2099 to run task
[2023-04-25T20:26:56.790+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather_dag_api', 'extract_data', 'manual__2023-04-25T20:26:33.610694+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag_api.py', '--cfg-path', '/tmp/tmpf0_zvlvt']
[2023-04-25T20:26:56.794+0000] {standard_task_runner.py:83} INFO - Job 21: Subtask extract_data
[2023-04-25T20:26:56.987+0000] {task_command.py:389} INFO - Running <TaskInstance: weather_dag_api.extract_data manual__2023-04-25T20:26:33.610694+00:00 [running]> on host 9dd0afd831d3
[2023-04-25T20:26:57.199+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_dag_api
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-25T20:26:33.610694+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-25T20:26:33.610694+00:00
[2023-04-25T20:26:57.207+0000] {http.py:123} INFO - Calling HTTP method
[2023-04-25T20:26:57.262+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 125, in execute
    response = http.run(self.endpoint, self.data, self.headers, self.extra_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 137, in run
    session = self.get_conn(headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 91, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `weather_conn/2023-04-25T13:20:00.000+03:00/t_2m:C/49.841952,24.0315921/json` isn't defined
[2023-04-25T20:26:57.276+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=weather_dag_api, task_id=extract_data, execution_date=20230425T202633, start_date=20230425T202656, end_date=20230425T202657
[2023-04-25T20:26:57.318+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 21 for task extract_data (The conn_id `weather_conn/2023-04-25T13:20:00.000+03:00/t_2m:C/49.841952,24.0315921/json` isn't defined; 2099)
[2023-04-25T20:26:57.377+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-25T20:26:57.484+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
