[2023-04-26T18:38:08.055+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag_api.cities.insert_data_Zhmerynka manual__2023-04-26T18:37:22.405033+00:00 [queued]>
[2023-04-26T18:38:08.156+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag_api.cities.insert_data_Zhmerynka manual__2023-04-26T18:37:22.405033+00:00 [queued]>
[2023-04-26T18:38:08.157+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T18:38:08.159+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-26T18:38:08.160+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T18:38:08.223+0000] {taskinstance.py:1309} INFO - Executing <Task(PostgresOperator): cities.insert_data_Zhmerynka> on 2023-04-26 18:37:22.405033+00:00
[2023-04-26T18:38:08.304+0000] {standard_task_runner.py:55} INFO - Started process 1848 to run task
[2023-04-26T18:38:08.357+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather_dag_api', 'cities.insert_data_Zhmerynka', 'manual__2023-04-26T18:37:22.405033+00:00', '--job-id', '346', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag_api.py', '--cfg-path', '/tmp/tmpnl8i9wsu']
[2023-04-26T18:38:08.365+0000] {standard_task_runner.py:83} INFO - Job 346: Subtask cities.insert_data_Zhmerynka
[2023-04-26T18:38:08.978+0000] {task_command.py:389} INFO - Running <TaskInstance: weather_dag_api.cities.insert_data_Zhmerynka manual__2023-04-26T18:37:22.405033+00:00 [running]> on host b46a99c748bd
[2023-04-26T18:38:09.405+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_dag_api
AIRFLOW_CTX_TASK_ID=cities.insert_data_Zhmerynka
AIRFLOW_CTX_EXECUTION_DATE=2023-04-26T18:37:22.405033+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-26T18:37:22.405033+00:00
[2023-04-26T18:38:09.412+0000] {sql.py:254} INFO - Executing: INSERT INTO measurements (temp) VALUES ("ti.xcom_pull('cities.process_data_Zhmerynka')")
[2023-04-26T18:38:09.451+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-04-26T18:38:12.785+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-04-26T18:38:12.825+0000] {sql.py:375} INFO - Running statement: INSERT INTO measurements (temp) VALUES ("ti.xcom_pull('cities.process_data_Zhmerynka')"), parameters: None
[2023-04-26T18:38:12.849+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "ti.xcom_pull('cities.process_data_Zhmerynka')" does not exist
LINE 1: INSERT INTO measurements (temp) VALUES ("ti.xcom_pull('citie...
                                                ^

[2023-04-26T18:38:12.898+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=weather_dag_api, task_id=cities.insert_data_Zhmerynka, execution_date=20230426T183722, start_date=20230426T183808, end_date=20230426T183812
[2023-04-26T18:38:12.986+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 346 for task cities.insert_data_Zhmerynka (column "ti.xcom_pull('cities.process_data_Zhmerynka')" does not exist
LINE 1: INSERT INTO measurements (temp) VALUES ("ti.xcom_pull('citie...
                                                ^
; 1848)
[2023-04-26T18:38:13.168+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-26T18:38:13.745+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
