[2023-04-26T17:51:45.490+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag_api.cities.insert_data_Kyiv manual__2023-04-26T17:50:52.913170+00:00 [queued]>
[2023-04-26T17:51:45.654+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag_api.cities.insert_data_Kyiv manual__2023-04-26T17:50:52.913170+00:00 [queued]>
[2023-04-26T17:51:45.656+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T17:51:45.658+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-26T17:51:45.660+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T17:51:45.757+0000] {taskinstance.py:1309} INFO - Executing <Task(PostgresOperator): cities.insert_data_Kyiv> on 2023-04-26 17:50:52.913170+00:00
[2023-04-26T17:51:45.804+0000] {standard_task_runner.py:55} INFO - Started process 457 to run task
[2023-04-26T17:51:45.840+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather_dag_api', 'cities.insert_data_Kyiv', 'manual__2023-04-26T17:50:52.913170+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag_api.py', '--cfg-path', '/tmp/tmp2ub3ga3_']
[2023-04-26T17:51:45.845+0000] {standard_task_runner.py:83} INFO - Job 60: Subtask cities.insert_data_Kyiv
[2023-04-26T17:51:47.239+0000] {task_command.py:389} INFO - Running <TaskInstance: weather_dag_api.cities.insert_data_Kyiv manual__2023-04-26T17:50:52.913170+00:00 [running]> on host b46a99c748bd
[2023-04-26T17:51:48.085+0000] {abstractoperator.py:615} ERROR - Exception rendering Jinja template for task 'cities.insert_data_Kyiv', field 'sql'. Template: 'INSERT INTO measurements (temp)  VALUES ({{ti.xcom_pull(task_ids=f"cities.process_data_Kyiv")[1]}});'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 607, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 661, in render_template
    template = jinja_env.from_string(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'string'
[2023-04-26T17:51:48.136+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1383, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1502, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2123, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 607, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 661, in render_template
    template = jinja_env.from_string(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'string'
[2023-04-26T17:51:48.310+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=weather_dag_api, task_id=cities.insert_data_Kyiv, execution_date=20230426T175052, start_date=20230426T175145, end_date=20230426T175148
[2023-04-26T17:51:48.573+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 60 for task cities.insert_data_Kyiv (expected token ',', got 'string'; 457)
[2023-04-26T17:51:48.819+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-26T17:51:49.113+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
