[2023-04-26T14:47:06.079+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag_api.cities.process_data_Zhmerynka manual__2023-04-26T14:46:43.897713+00:00 [queued]>
[2023-04-26T14:47:06.266+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag_api.cities.process_data_Zhmerynka manual__2023-04-26T14:46:43.897713+00:00 [queued]>
[2023-04-26T14:47:06.269+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T14:47:06.270+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-26T14:47:06.272+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T14:47:06.355+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): cities.process_data_Zhmerynka> on 2023-04-26 14:46:43.897713+00:00
[2023-04-26T14:47:06.473+0000] {standard_task_runner.py:55} INFO - Started process 1823 to run task
[2023-04-26T14:47:06.648+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather_dag_api', 'cities.process_data_Zhmerynka', 'manual__2023-04-26T14:46:43.897713+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag_api.py', '--cfg-path', '/tmp/tmp4_t_wfko']
[2023-04-26T14:47:06.663+0000] {standard_task_runner.py:83} INFO - Job 48: Subtask cities.process_data_Zhmerynka
[2023-04-26T14:47:07.554+0000] {task_command.py:389} INFO - Running <TaskInstance: weather_dag_api.cities.process_data_Zhmerynka manual__2023-04-26T14:46:43.897713+00:00 [running]> on host d48b88797b3b
[2023-04-26T14:47:09.098+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_dag_api
AIRFLOW_CTX_TASK_ID=cities.process_data_Zhmerynka
AIRFLOW_CTX_EXECUTION_DATE=2023-04-26T14:46:43.897713+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-26T14:46:43.897713+00:00
[2023-04-26T14:47:09.105+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 173, in execute
    self.op_kwargs = self.determine_kwargs(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 184, in determine_kwargs
    return KeywordParameters.determine(self.python_callable, self.op_args, context).unpacking()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/operator_helpers.py", line 161, in determine
    raise ValueError(f"The key {name!r} in args is a part of kwargs and therefore reserved.")
ValueError: The key 'ti' in args is a part of kwargs and therefore reserved.
[2023-04-26T14:47:09.206+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=weather_dag_api, task_id=cities.process_data_Zhmerynka, execution_date=20230426T144643, start_date=20230426T144706, end_date=20230426T144709
[2023-04-26T14:47:09.372+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 48 for task cities.process_data_Zhmerynka (The key 'ti' in args is a part of kwargs and therefore reserved.; 1823)
[2023-04-26T14:47:09.548+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-26T14:47:10.118+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
