[2023-04-26T15:01:22.416+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag_api.cities.process_data_Kharkiv manual__2023-04-26T15:00:51.829131+00:00 [queued]>
[2023-04-26T15:01:22.563+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag_api.cities.process_data_Kharkiv manual__2023-04-26T15:00:51.829131+00:00 [queued]>
[2023-04-26T15:01:22.571+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T15:01:22.587+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-26T15:01:22.592+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T15:01:22.867+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): cities.process_data_Kharkiv> on 2023-04-26 15:00:51.829131+00:00
[2023-04-26T15:01:22.912+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather_dag_api', 'cities.process_data_Kharkiv', 'manual__2023-04-26T15:00:51.829131+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag_api.py', '--cfg-path', '/tmp/tmpz40qz3wq']
[2023-04-26T15:01:22.920+0000] {standard_task_runner.py:83} INFO - Job 75: Subtask cities.process_data_Kharkiv
[2023-04-26T15:01:22.916+0000] {standard_task_runner.py:55} INFO - Started process 2129 to run task
[2023-04-26T15:01:23.477+0000] {task_command.py:389} INFO - Running <TaskInstance: weather_dag_api.cities.process_data_Kharkiv manual__2023-04-26T15:00:51.829131+00:00 [running]> on host d48b88797b3b
[2023-04-26T15:01:23.986+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_dag_api
AIRFLOW_CTX_TASK_ID=cities.process_data_Kharkiv
AIRFLOW_CTX_EXECUTION_DATE=2023-04-26T15:00:51.829131+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-26T15:00:51.829131+00:00
[2023-04-26T15:01:24.059+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/weather_dag_api.py", line 31, in process_weather_data
    print(info["data"][0]["coordinates"][0]["dates"][0]["value"])
TypeError: 'NoneType' object is not subscriptable
[2023-04-26T15:01:24.124+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=weather_dag_api, task_id=cities.process_data_Kharkiv, execution_date=20230426T150051, start_date=20230426T150122, end_date=20230426T150124
[2023-04-26T15:01:24.295+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 75 for task cities.process_data_Kharkiv ('NoneType' object is not subscriptable; 2129)
[2023-04-26T15:01:24.375+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-26T15:01:24.914+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
