[2023-04-26T18:02:04.564+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag_api.cities.insert_data_Lviv manual__2023-04-26T18:01:23.791505+00:00 [queued]>
[2023-04-26T18:02:04.646+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag_api.cities.insert_data_Lviv manual__2023-04-26T18:01:23.791505+00:00 [queued]>
[2023-04-26T18:02:04.654+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T18:02:04.659+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-26T18:02:04.664+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T18:02:04.863+0000] {taskinstance.py:1309} INFO - Executing <Task(PostgresOperator): cities.insert_data_Lviv> on 2023-04-26 18:01:23.791505+00:00
[2023-04-26T18:02:04.942+0000] {standard_task_runner.py:55} INFO - Started process 815 to run task
[2023-04-26T18:02:04.985+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather_dag_api', 'cities.insert_data_Lviv', 'manual__2023-04-26T18:01:23.791505+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag_api.py', '--cfg-path', '/tmp/tmpvda577mo']
[2023-04-26T18:02:04.989+0000] {standard_task_runner.py:83} INFO - Job 149: Subtask cities.insert_data_Lviv
[2023-04-26T18:02:05.707+0000] {task_command.py:389} INFO - Running <TaskInstance: weather_dag_api.cities.insert_data_Lviv manual__2023-04-26T18:01:23.791505+00:00 [running]> on host b46a99c748bd
[2023-04-26T18:02:06.870+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_dag_api
AIRFLOW_CTX_TASK_ID=cities.insert_data_Lviv
AIRFLOW_CTX_EXECUTION_DATE=2023-04-26T18:01:23.791505+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-26T18:01:23.791505+00:00
[2023-04-26T18:02:06.874+0000] {sql.py:254} INFO - Executing: INSERT INTO measurements (temp) VALUES (15.1);
[2023-04-26T18:02:07.319+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 255, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 179, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 141, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2023-04-26T18:02:07.418+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=weather_dag_api, task_id=cities.insert_data_Lviv, execution_date=20230426T180123, start_date=20230426T180204, end_date=20230426T180207
[2023-04-26T18:02:07.555+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 149 for task cities.insert_data_Lviv (The conn_id `postgres_default` isn't defined; 815)
[2023-04-26T18:02:07.694+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-26T18:02:07.815+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
